sudo: required
dist: trusty
language: node_js
node_js: 7
branches:
  only:
    - master
    - nightly
deploy:
  provider: heroku
  app:
    master: tp314rates
    nightly: project-motion
  api_key:
    master:
      secure: xV7yOohEIQ0rM6q/hdGyPgQFwETM93F7aUN4h2zbnZjqFpG9zmpyGTrg+u3FIMAuOFDZn+mzIdikr88B67E7jUVyd9lwbeka9LYVFmwvHH4VBtiNuliWfl3Paa5TrQx8Ha+WBHSBgotyYFw2MVowy2d8OT+ZSIHgRBmdLPbfyOk2HtBkLP7urJltuA+2jJCuAg2ybgvhfSfuKvMjZIdPVePz2VGV8w3RfxJl8LJp1QJBHCzHHhlGOu6ngTEGtq2w1soGAK/tAkgbv9AwPHLuI3zvuNMsShl6/6bAemEMh9AyYUTkuZHAxNjIFkVZOEr9A4OK2AXWqm6ATDQD9tnQbz7LgPAzyQW8ZLjYEiZY/oKbzrOihGJt7Miogmyy4R8nsPHlymJ8hCncxEcuogcE9n/Xkc86D/EwqDUaz3TbCKxaYbOdZ/4YWaCmZxHoiDSyqvytWKK0KZy6jAWg4hEmO8S8HT/Oy9Ox4GeDbpfEsOCLEBk+DOXGncFWcD4i2nskdzPgYOSmcWKGXX+GRhb9n/n8MAn0WBQGNfLVzdJ25+9T2Y+0foyKu090ywiqYDRnsnO/vq/uWUA6Wh5DCIMSEQ45XxGt4/g2T4wpgdHRc9PIqdvmuBResTwPMXIyhCNdMBARhR6KuJLnVAzUupZxL9OCxF5pm0TtSFigzmf1KSs=
    nightly:
      secure: dhCOhf/YggCuBQdq1poB4jxQzi1Y89y82uFjlL/zijPqH76hVsKmNFIMe6ZnywrGUK4pJonrj9JSIbH7fFmAehHgTVA5eN10rl/kiiyAFoaq5GYH/9eR2fx6IB3L8teA2jIp3K76hPNvLOYQUIrdJzsJV7zg+V2jHaDNvu4ePSegLVB33jYTGlLdtwry50YviJdbYz67Dlzqxcw94yDwYw5btdhyrNuZ13I/FDNI0jSq1cYqn1vWJoaaUG2LI8xSDbrJrcFXwzxdM3JYIlChTUdT2qdxot/WQhQTAQ5vEBi1KUTiZqcfxoZe1pdhHGIW7WQzrvJdJw9KZcGT4ZaZOiSaEes6z8vqHUHgyX+GZyMzDkGXxhesuz1ywLvhbyiWBrSQ06vwRdrwA/iTKkIU2vdcPzNnne0qoimo0Wc1f1mDwP0izjDuirc4l/UVhuxeHxAZ/oquPddNX6GJKmADd2XSKA18MvJ3BO6+x+Go+caz8Rt1Q76jS8q7Q03/ah0y4Y3TosZCtX2dtnZ+WShqoagkrxzfqAcko4ij6dYUbs6EAMZykSdYlDxq75jyDieThcNLh2EAXOw5qJwTJtjS2YQM0K5PMPAQQxZlRWuzlA2e3pUzcmy7cDwOwglP/6bvma//+gulaiec0O2RPudZjuR3vXSi4irS21pDuzkVdQw=
